# Programming Drill 2.2.1 Convert your functions from the last programming drill so that instead of accepting elements of $ \mathbb{C}^n $ they accept elements of $ \mathbb{C}^{m \times n} $.

Yanofsky, Noson S.. Quantum Computing for Computer Scientists (p. 39). Cambridge University Press. Kindle Edition. 

Thanks to the `numpy` based implementation of the last exercise, we have very minimal to chagne for this one. Let's go

In [1]:
import numpy as np

In [2]:
class Vector(object):
    """
    Similar like the previous chapter examples, we define a Vector class now
    
    The method names and their work is self explainatory
    """
    def __init__(self, elements: list):
        self.vector = np.array(elements)
    
    def __add__(self, other):
        """
        Over-riding the '+' operation for vectors
        """
        return self.vector + other.vector
    
    def __radd__(self, other):
        """
        And the reverse add operation as well.
        """
        return self.vector + other
    
    def scalar_multiply(self, scalar):
        return scalar * self.vector
    
    def additive_inverse(self):
        return Vector(self.scalar_multiply(-1)) 

In [17]:
v1 = Vector([[1-1j, 3], [2+2j, 4+1j]])  # Just the shape of the input array changes

In [18]:
v2 = v1.additive_inverse()

In [19]:
v2.vector

array([[-1.+1.j, -3.+0.j],
       [-2.-2.j, -4.-1.j]])

In [20]:
scalar1 = 0+2j

In [21]:
scalar2 = 1+2j

In [22]:
v3 = v1.scalar_multiply(scalar1)

In [23]:
v3

array([[ 2.+2.j,  0.+6.j],
       [-4.+4.j, -2.+8.j]])

In [25]:
v4 = v1.scalar_multiply(scalar2)
v4

array([[ 3.+1.j,  3.+6.j],
       [-2.+6.j,  2.+9.j]])

In [26]:
v5 = v3 + v4

In [28]:
v5

array([[ 5. +3.j,  3.+12.j],
       [-6.+10.j,  0.+17.j]])