# Programming Drill 3.2.1 Modify your program from Programming Drill 3.1.1 so that the entries in the matrices can be fractions as opposed to Boolean values.

Yanofsky, Noson S.. Quantum Computing for Computer Scientists (p. 88). Cambridge University Press. Kindle Edition. 

We will use the same idea from the last exercise but we will modify the check to check for doubly stochastic matrix

In [2]:
import numpy as np
from numpy.linalg import matrix_power

In [3]:
def change_state(M, init_state, time_click, doubly_stochastic=True):
    if doubly_stochastic:
        col_sums = np.sum(M, axis=0)
        if np.max(col_sums) > 1:
            print("The matrix does not comply to our need, because of columns")
            return None
        row_sums = np.sum(M, axis=1)
        if np.max(row_sums) > 1:
            print("The matrix does not comply to our need, because of rows")
            return None
    final_matrix = matrix_power(M, time_click)
    return np.matmul(final_matrix, init_state.transpose()).transpose()

### Billiard Ball Experiment

In [4]:
A = np.array([[0, 0.5, 0.5, 0], [0.5, 0, 0, 0.5], [0.5, 0, 0, 0.5], [0, 0.5, 0.5, 0]])

In [5]:
t0 = np.array([[1, 0, 0, 0]])

In [6]:
change_state(A, t0, 1)

array([[0. , 0.5, 0.5, 0. ]])

In [7]:
change_state(A, t0, 2)

array([[0.5, 0. , 0. , 0.5]])

In [12]:
change_state(A, t0, 3)

array([[0. , 0.5, 0.5, 0. ]])

### Double slit experiment (With bullets, classical probability)

In [8]:
half = 0.5
one_third = float(1/3)
B = np.array([[0, 0, 0, 0, 0, 0, 0, 0,],
              [half, 0, 0, 0, 0, 0, 0, 0],
              [half, 0, 0, 0, 0, 0, 0, 0],
              [0, one_third, 0, 1, 0, 0, 0, 0],
              [0, one_third, 0, 0, 1, 0, 0, 0],
              [0, one_third, one_third, 0, 0, 1, 0, 0],
              [0, 0, one_third, 0, 0, 0, 1, 0],
              [0, 0, one_third, 0, 0, 0, 0, 1]])

In [9]:
X = np.array([[1, 0, 0, 0, 0, 0, 0, 0]])

In [10]:
change_state(B, X, 2, doubly_stochastic=False)

array([[0.        , 0.        , 0.        , 0.16666667, 0.16666667,
        0.33333333, 0.16666667, 0.16666667]])

In [11]:
float(1/6)

0.16666666666666666